### ISSUE TITLE
Nice idea, couple of small issues

### ISSUE THREAD

**Issue by kidGodzilla** [matiasvlevi/gptdoc#2] opened 2023-04-01 02:39 UTC
Love the idea! Will test it out again when I have some more time.

Thought I'd leave a comment with a couple of issues in case you weren't aware of them.

1. There's an error if .gptdoc isn't present or explicitly define (which may be intentional) -- but it isn't included by default in the repo to run the `docself` task or tests, so I thought I'd mention it.

<img width="1081" alt="Screenshot 2023-03-31 at 7 37 00 PM" src="https://user-images.githubusercontent.com/6320214/229261884-22f38361-ad98-4ee0-b02e-a05f09f4f370.png">

2. This seems to rely on built-in `fetch` API, so it doesn't work in Node < v18

**Comment by matiasvlevi** [comment] 2023-04-01 20:35
Hey,
Thanks for pointing out these issues!

For the missing configuration file, I can confirm, it wasn't intentional, It is now fixed (commit 781b46b).

As for the use of the nodejs fetch API, I prefer leaving it unchanged, as it is supported in the lts release of nodejs, and I prefer leaving no dependencies in the project. 

I have restricted the engine version to `^18.0.0` as of commit 165db3e

If a backwards compatible version of gptdoc is required, I suggest someone creates a fork using something like `axios` or `node:https` (requests source code can be found in `./src/gpt.ts`).

I am leaving this issue open, since I left the fetch API in the project.

Thanks again for your insight!

**Closed as completed** 2023-04-23 20:03 UTC
